yii2-shop/frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use common\models\Order;
use common\models\OrderItem;
use common\models\Product;
use yz\shoppingcart\ShoppingCart;

class CartController extends \yii\web\Controller
{
    public function actionAdd($id)
    {

        $product = Product::findOne($id);
//        print_r($product);
//        exit;
        if ($product) {
            \Yii::$app->cart->put($product);
            return $this->goBack();
        }
    }

    public function actionList()
    {
        /* @var $cart ShoppingCart */
        $cart = \Yii::$app->cart;

        $products = $cart->getPositions();
        $total = $cart->getCost();

        return $this->renderPartial('list', [
           'products' => $products,
           'total' => $total,
        ]);
    }

    public function actionRemove($id)
    {
        $product = Product::findOne($id);
        if ($product) {
            \Yii::$app->cart->remove($product);

            $cart = \Yii::$app->cart;

            $products = $cart->getPositions();
            $total = $cart->getCost();

            return $this->renderPartial('list', [
                'products' => $products,
                'total' => $total,
            ]);
        }
    }

    public function actionUpdate($id, $quantity)
    {
        $product = Product::findOne($id);
        if ($product) {
            \Yii::$app->cart->update($product, $quantity);

            $cart = \Yii::$app->cart;

            $products = $cart->getPositions();
            $total = $cart->getCost();

            return $this->renderPartial('list', [
                'products' => $products,
                'total' => $total,
            ]);
//            $this->redirect(['cart/list']);
        }
    }

    public function actionOrder()
    {
        $order = new Order();

        /* @var $cart ShoppingCart */
        $cart = \Yii::$app->cart;

        /* @var $products Product[] */
        $products = $cart->getPositions();
        $total = $cart->getCost();

        if(\Yii::$app->request->isAjax && $order->load(\Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }


        if ($order->load(\Yii::$app->request->post()) && $order->validate()) {
            $transaction = $order->getDb()->beginTransaction();
            $order->save(false);

            foreach($products as $product) {
                $orderItem = new OrderItem();
                $orderItem->sku = $product->sku;
                $orderItem->order_id = $order->id;
                $orderItem->title = $product->title;
                $orderItem->price = $product->getPrice();
                $orderItem->product_id = $product->id;
                $orderItem->quantity = $product->getQuantity();
                if (!$orderItem->save(false)) {
                    $transaction->rollBack();
                    \Yii::$app->session->addFlash('error', 'Cannot place your order. Please contact us.');
                    return $this->redirect('/');
                }
            }

            $transaction->commit();
            \Yii::$app->cart->removeAll();

            \Yii::$app->session->addFlash('success', 'Thanks for your order. We\'ll contact you soon.');
            $order->sendEmail();

            return $this->redirect('/');
        }

        return $this->renderPartial('list', [
            'order' => $order,
            'products' => $products,
            'total' => $total,
        ]);
    }
}

yii2-shop/frontend/views/cart/list.php
<?php
use \yii\helpers\Html;
use himiklab\thumbnail\EasyThumbnailImage;

/* @var $this yii\web\View */
/* @var $products common\models\Product[] */

?>

<div class="cart_issue">
    <table class="bodyTable">
        <thead>
        <tr>
            <td>Фото</td>
            <td>Наименование</td>

            <td>Количество</td>
            <td>Цена</td>
            <td>Итого</td>
            <td></td>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($products as $product):?>
            <tr>
                <td>
                    <?
//                    print_r($product->images);
                    $img=EasyThumbnailImage::thumbnailImg(
                            $product->goods->images[0]->getPath(),
                            55,
                            55,
                            EasyThumbnailImage::THUMBNAIL_OUTBOUND,
                            ['alt' =>$product->goods->images[0]->id]);
                    ?>
                    <a href="<??>">

                        <?=$img?>
                    </a>
                </td>
                <td>
                    <a href="<?=\yii\helpers\Url::toRoute(['catalog/view','id'=>$product->goods_id])?>" class="url">
                        <?= Html::encode($product->title) ?> </a>
                </td>

                <td>


                    <div class="btn btn-small updateCart"  data_id="<?=$product->id?>" data_val="<?=($product->getQuantity()-1)?>">-</div>

<!--                    --><?//= Html::a('-', '#', ['class' => 'btn btn-small updateCart','data_val'=>($product->getQuantity()-1)])?>
                    <div class="count" contenteditable="true" ><?=$product->getQuantity()?></div>
                    <div class="btn btn-small updateCart" data_id="<?=$product->id?>" data_val="<?=($product->getQuantity()+1)?>">+</div>
<!--                    --><?//= Html::span('+', '#', ['class' => 'btn btn-small updateCart','data-val'=>($product->getQuantity()+1)])?>
<!--                    --><?//= Html::a('×', ['cart/remove', 'id' => $product->getId()], ['class' => 'remove'])?>
                </td>
                <td>
                     <span class="priceNum"><?= $product->Price ?> </span>грн.
                </td>
                <td>
                     <span class="totalNum"><?=$product->getCost()?> </span>грн.
                </td>
                <td>
                    <div class="btn btn-small deleteCart" data_val="<?=$product->id?>">x</div>
                </td>







            </tr>
        <?php endforeach ?>

        </tbody>
    </table>
    <div class="fullTotal">
        Сумма:
                        <span class="fullNum">
                             <?= $total ?>            </span>грн.
    </div>
</div>

<script>

    $('.updateCart').on('click',function(){
        $.ajax({
            type: "GET",
            url: "/cart/update/?id="+$(this).attr('data_id')+'&quantity='+$(this).attr('data_val'),
            success: function(msg){
//                alert(msg)
                $( "#cartFormItems").html(msg)
            }
        });
    });


    $('.deleteCart').on('click',function(){
        $.ajax({
            type: "GET",
            url: "/cart/remove/?id="+$(this).attr('data_val'),
            success: function(msg){
                $( "#cartFormItems").html(msg)
            }
            })
        });


</script>

yii2-shop/frontend/views/cart/order.php
<?php
use \yii\helpers\Html;
use \yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $products common\models\Product[] */
?>
<h1>Your order</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-4">

        </div>
        <div class="col-xs-2">
            Price
        </div>
        <div class="col-xs-2">
            Quantity
        </div>
        <div class="col-xs-2">
            Cost
        </div>
    </div>
    <?php foreach ($products as $product):?>
    <div class="row">
        <div class="col-xs-4">
            <?= Html::encode($product->title) ?>
        </div>
        <div class="col-xs-2">
            $<?= $product->price ?>
        </div>
        <div class="col-xs-2">
            <?= $quantity = $product->getQuantity()?>
        </div>
        <div class="col-xs-2">
            $<?= $product->getCost() ?>
        </div>
    </div>
    <?php endforeach ?>
    <div class="row">
        <div class="col-xs-8">

        </div>
        <div class="col-xs-2">
            Total: $<?= $total ?>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <?php
            /* @var $form ActiveForm */
            $form = ActiveForm::begin([
                'id' => 'order-form',
            ]) ?>

            <?= $form->field($order, 'phone') ?>
            <?= $form->field($order, 'email') ?>
            <?= $form->field($order, 'notes')->textarea() ?>

            <div class="form-group row">
                <div class="col-xs-12">
                    <?= Html::submitButton('Order', ['class' => 'btn btn-primary']) ?>
                </div>
            </div>

            <?php ActiveForm::end() ?>
        </div>
    </div>
</div>