yii2-shop/frontend/controllers/CatalogController.php
<?php

namespace frontend\controllers;

use common\models\Category;
use common\models\Goods;
use common\models\Product;
use common\models\Params;
use yii\widgets\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\web\Response;
use Yii;

class CatalogController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            Url::remember();
            return true;
        } else {
            return false;
        }
    }

    public function actionList($id = null)
    {
//        \Yii::$app->cart->removeAll();
        /** @var Category $category */
        $category = null;


        $categories = Category::find()->indexBy('id')->orderBy('id')->all();


        $productsQuery = Goods::find();
        if ($id !== null && isset($categories[$id])) {
            $category = $categories[$id];
            $productsQuery->where(['category_id' => $this->getCategoryIds($categories, $id)]);
        }
        else
        {
            $productsQuery->andWhere(['popular'=>1]);
        }

        $productsQuery->andWhere(['status'=>Goods::STATUS_ACTIVE]);

        $productsDataProvider = new ActiveDataProvider([
            'query' => $productsQuery,
            'pagination' => [
                'pageSize' => ($id!=null ? 50 : 8),
            ],
        ]);


        return $this->render('list', [
            'category' => $category,
            'menuItems' => $this->getMenuItems($categories, isset($category->id) ? $category->id : null),
            'productsDataProvider' => $productsDataProvider,
        ]);
    }

    public function actionView($id)
    {
        $model=new Product(['scenario'=>'addToCard']);

        $model->goods_id=$id;

        $product=Goods::findOne($id);
        if($product->status==0)
        {
            return $this->redirect(['/']);
        }
        $productPopular=Goods::find()->where(['popular'=>1,'status'=>Goods::STATUS_ACTIVE])->orderBy('RAND()')->limit(5)->all();



        $model->load(Yii::$app->request->post());

        if(Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        $item=Product::find()->where(['goods_id'=>$id,'color'=>$model->color,'size'=>$model->size])->one();
        if($item->sku)
        {
            return $this->redirect(['cart/add', 'id' => $item->id]);
        }

        $prev = Goods::find()->where(['<','id',$id])->andWhere(['status'=>Goods::STATUS_ACTIVE])->one();
        $next = Goods::find()->where(['>','id',$id])->andWhere(['status'=>Goods::STATUS_ACTIVE])->one();;
        $categories = Category::find()->indexBy('id')->orderBy('id')->all();

        return $this->render('view',[
            'menuItems' => $this->getMenuItems($categories, isset($category->id) ? $category->id : null),
            'product' => $product,
            'productPopular' => $productPopular,
            'model' => $model,
            'colors'=>$product->colors,
            'sizes'=>$product->sizes,
            'prev' => $prev,
            'next' => $next,
            ]
    );
    }

    public function actionFilter($id)
    {
        $model=new Product(['scenario'=>'addToCard']);

        $model->load(Yii::$app->request->post());
        $model->goods_id=$id;
        //colors

        if($model->color!='')
        {
            $colors=Product::find()->select('size')->distinct('size')->where(['color'=>$model->color,'goods_id'=>$id])->andWhere(['>','sku','0'])->all();
        }
        else
        {
            $colors=Product::find()->select('size')->distinct('size')->where(['goods_id'=>$id])->andWhere(['>','sku','0'])->all();
        }

        foreach($colors as $c)
        {
            $tmpC[]=$c->size;

        }
        //sizes

        if($model->size!='')
        {
            $sizes=Product::find()->select('color')->distinct('color')->where(['size'=>$model->size,'goods_id'=>$id])->andWhere(['>','sku','0'])->all();

        }
        else
        {
            $sizes=Product::find()->select('color')->distinct('color')->where(['goods_id'=>$id])->andWhere(['>','sku','0'])->all();
        }
        foreach($sizes as $c)
        {
            $tmpS[]=$c->color;

        }
//        $colors=Params::find()->where(['id'=>$tmpS])->asArray()->all();
        $colors=Params::find()->where(['id'=>$tmpS])->all();
//        $sizes=Params::find()->where(['id'=>$tmpC])->asArray()->all();
        $sizes=Params::find()->where(['id'=>$tmpC])->all();
//        print_r($colors);
//        print_r($sizes);
//        exit;


            return $this->renderPartial('filterAttr2',[
                'changeAttr'=>$changeAttr,
                'res'=>$res,
                'colors'=>$colors,
                'sizes'=>$sizes,
                'model'=>$model,
            ]);
    }

    public function activeValidation()
    {

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $errors=ActiveForm::validate($model);
            return $errors;
        }
    }

    /**
     * @param Category[] $categories
     * @param int $activeId
     * @return array
     */
    private function getMenuItems($categories, $activeId = null)
    {
        $menuItems = [];
        foreach ($categories as $category) {
            if ($category->parent_id === 0) {
                $menuItems[$category->id] = [
                    'active' => $activeId === $category->id,
                    'label' => $category->title,
                    'url' => ['catalog/list', 'id' => $category->id],
                ];
            } else {
                $this->placeCategory($category, $menuItems, $activeId);
            }
        }
        return $menuItems;
    }

    /**
     * Places category menu item into menu tree
     *
     * @param Category $category
     * @param $menuItems
     * @param int $activeId
     */
    private function placeCategory($category, &$menuItems, $activeId = null)
    {
        foreach ($menuItems as $id => $navLink) {
            if ($category->parent_id === $id) {
                $menuItems[$id]['items'][$category->id] = [
                    'active' => $activeId === $category->id,
                    'label' => $category->title,
                    'url' => ['catalog/list', 'id' => $category->id],
                ];
                break;
            } elseif (!empty($menuItems[$id]['items'])) {
                $this->placeCategory($category, $menuItems[$id]['items']);
            }
        }
    }

    /**
     * Returns IDs of category and all its sub-categories
     *
     * @param Category[] $categories all categories
     * @param int $categoryId id of category to start search with
     * @param array $categoryIds
     * @return array $categoryIds
     */
    private function getCategoryIds($categories, $categoryId, &$categoryIds = [])
    {
        foreach ($categories as $category) {
            if ($category->id == $categoryId || $category->parent_id == $categoryId) {
                $categoryIds[] = $category->id;
            }
            if (isset($categories[$categoryId]['items'])) {
                foreach ($categories[$categoryId]['items'] as $subCategoryId => $subCategory)
                $this->getCategoryIds($categories, $subCategoryId, $categoryIds);
            }
        }
        return $categoryIds;
    }
}

yii2-shop/frontend/views/catalog/_product.php
<?php
use yii\helpers\Html;
use yii\helpers\Markdown;
use himiklab\thumbnail\EasyThumbnailImage;
?>
<?php /** @var $model \common\models\Product */ ?>



<div class="goods1 span3">
    <a href="<?=\yii\helpers\Url::toRoute(['catalog/view','id'=>$model->id])?>"><div class="goods_wrap_img">
            <?php
            $images = $model->images;
            if (isset($images[0])) {
                echo  EasyThumbnailImage::thumbnailImg(
                    $images[0]->getPath(),
                    500,
                    700,
                    EasyThumbnailImage::THUMBNAIL_INSET,
                    ['alt' => $images[0]->id]
                );
            }
            ?>
        </div>
    </a>
    <div class="price">
        <div class="price_mini">
            <p><?= Html::encode(round($model->product->price,2)) ?> грн.</p>
            <p><span>в наличии</span></p>
        </div>
        <div class="cart_buttun">
            <a href="<?=\yii\helpers\Url::toRoute(['catalog/view','id'=>$model->id])?>"> Подробнее</a>
        </div>
        <div class="clear"></div>
        <div class="description">
            <p><?=$model->description?></p>
        </div>
    </div>
</div>

yii2-shop/frontend/views/catalog/filterAttr.php
<?php
/**
 * Created by PhpStorm.
 * User: awelara
 * Date: 27.05.15
 * Time: 16:38
 */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
?>
    <ul>

        <?  foreach($res as $c){
            if($changeAttr=='color'){
            ?><li><a id="product-<?=$changeAttr?> option[value='<?=$c->id?>']" dataid="<?=$c->id?>" style="background: <?=mb_strtolower($c->value)?>;" class="product-<?=$changeAttr?>" ></a></li>
        <?}
            else{?>
                        <li><a class="product-<?=$changeAttr?>" id="product-size option[value='<?=$c->id?>']"  dataid="<?=$c->id?>" ><?=mb_strtolower($c->value)?></a></li>
            <?}
        } ?>
    </ul>
    <div class="form-group field-product-<?=$changeAttr?> required">
    <select id="product-<?=$changeAttr?>" class="form-control" name="Product[<?=$changeAttr?>]" style="display:block">
        <option value="">Select <?=$changeAttr?></option>
<? foreach($res as $c){
    ?>
    <option value="<?=$c->id?>"><?=$c->label?></option>
<?
}?>
    </select>
        <div class="help-block"></div>
    </div>
    <div class="clear"></div>

yii2-shop/frontend/views/catalog/filterAttr2.php
<?php
/**
 * Created by PhpStorm.
 * User: awelara
 * Date: 27.05.15
 * Time: 16:38
 */

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;


//print_r($res);
//print_r($model);


$form = ActiveForm::begin([
    'id'=>'form-filter',
    'enableAjaxValidation' => true,
//                'enableClientValidation' => true,
    'validateOnSubmit'=>true,
    'validateOnChange'=>true,
]);
?>

<?= Html::submitButton(Yii::t('app', 'В корзину'), ['class' => 'mini_cart_right helpful6']) ?>

    <div class="clear"></div>

    <p class="in_stock">В наличии</p>
    <div class="description_right">
        <?= $form->field($model, 'sku')->label(false)->textInput(['maxlength' => 10,'style'=>'display:none']) ?>
    </div>

    <div class="select_color" >
        <h4>Выбор цвета:</h4>
        <ul>

            <?  foreach($colors as $c){
                ?><li><a id="product-color option[value='<?=$c->id?>']" dataid="<?=$c->id?>" style="background: <?=mb_strtolower($c->value)?>;" class="product-color <?=(($c->id==$model->color) ? "border" : "" )?>" ></a></li>
            <?
            } ?>
        </ul>
        <?= $form->field($model, 'color')->label(false)->dropDownList(ArrayHelper::map($colors, 'id', 'label'), ['prompt' => 'Select color','style'=>'display:none']) ?>
        <div class="clear"></div>
    </div>


    <div class="select_size" >
        <h4>Выбор размера:</h4>
        <ul>
            <?  foreach($sizes as $c){
                ?><li><a class="product-size <?=(($c->id==$model->size) ? "border-size" : "" )?>" id="product-size option[value='<?=$c->id?>']"  dataid="<?=$c->id?>" ><?=mb_strtolower($c->value)?></a></li>
            <?
            } ?>
        </ul>
        <?= $form->field($model, 'size')->label(false)->dropDownList(ArrayHelper::map($sizes, 'id', 'label'), ['prompt' => 'Select size','style'=>'display:none']) ?>

        <div class="clear"></div>
    </div>



<?php ActiveForm::end(); ?>

yii2-shop/frontend/views/catalog/list.php
<?php
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ListView;
use yii\widgets\Menu;
use frontend\widgets\MenuBase;

/* @var $this yii\web\View */
$title = $category === null ? 'Популярные товары' : $category->title;
$this->title = Html::encode($title);
?>
<div class="container">
    <div class="seo_text"></div>
    <div class="clear"></div>
    <?if ($category === null){?>
    <div class="slider">
        <div id="da-slider" class="da-slider">
            <div class="da-slide">
                <h2>ГОЛЬФ ЖЕНСКИЙ</h2>
                <p>Наша торговая марка предлагает качественный трикотаж оптом и в розницу. У нас Вы найдете одежду на любой вкус, сможете оценить разнообразие цветовой гаммы и моделей.</p>
                <a href="http://golfo.com.ua/catalog/view?id=9" class="da-link">Купить</a>
                <div class="da-img"><img src="/img/T-shirt.png"></div>
            </div>
            <div class="da-slide">
                <h2>Футболки мужские</h2>
                <p>Оптом и в розницу. У нас низкие цены и большой выбор! Новая коллекция 2015.</p>
                <a href="http://golfo.com.ua/catalog/view?id=22" class="da-link">Купить</a>
                <div class="da-img"><img src="/img/T-shirt2.png"></div>
            </div>

            <nav class="da-arrows">
                <span class="da-arrows-prev"></span>
                <span class="da-arrows-next"></span>
            </nav>
        </div>
    </div>
    <?}?>


    <?

    $script = <<< JS
   $(function () {

            $('#da-slider').cslider({
                bgincrement: 0,
                autoplay: true
            });

        });
JS;
    $this->registerJs($script, View::POS_END);
    ?>

    <div class="clear"></div>
<div class="circles">

    <?

    echo \frontend\widgets\Menu::widget();
    ?>
</div>
<div class="clear"></div>
</div>

<div class="popular">
    <div class="container">
        <h1><?=$this->title?></h1>


          <?= ListView::widget([
              'dataProvider' => $productsDataProvider,
              'itemView' => '_product',
              'layout'=>'{items}'
          ]) ?>
</div>

yii2-shop/frontend/views/catalog/view.php
<?php
/* @var $this yii\web\View */
use himiklab\thumbnail\EasyThumbnailImage;
use yii\widgets\ActiveForm;
use yii\web\View;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

?>


<br>
<div class="clear"></div>
</div>


<div class="card_product">
<div class="container">
<div class="block_left span3">

        <?

        echo \frontend\widgets\MenuBase::widget();
        ?>
    <div class="clear"></div>


</div>
<div class="block_right span9">
<h1><?=$product->name?></h1>
<div class="main_left span5">

    <div id="main" role="main">
        <section class="slider2">
            <div id="slider" class="flexslider">
                <ul class="slides">

                    <?
                     foreach($product->images as $image){

                         echo  ' <li>'.EasyThumbnailImage::thumbnailImg(
                             $image->getPath(),
                             500,
                             700,
                             EasyThumbnailImage::THUMBNAIL_INSET,
                             ['alt' => $image->id]
                         ).'</li>';

                     }


                    ?>

                </ul>
            </div>
            <div id="carousel" class="flexslider">
                <ul class="slides">

                    <?
                    foreach($product->images as $image){

                        echo  ' <li>'.EasyThumbnailImage::thumbnailImg(
                                $image->getPath(),
                                109,
                                76,
                                EasyThumbnailImage::THUMBNAIL_OUTBOUND,
                                ['alt' => $image->id]
                            ).'</li>';
                    }
                    ?>
                </ul>
            </div>
        </section>

    </div>
</div>
<div class="main_right span3">
    <div class="top_nav">
        <?if($prev->id){?>
        <a href="<?=\yii\helpers\Url::toRoute(['catalog/view','id'=>$prev->id])?>"><< Предыдущий товар </a>
        <?}?>|
        <?if($next->id){?>
        <a href="<?=\yii\helpers\Url::toRoute(['catalog/view','id'=>$next->id])?>">Следующий товар >></a>
        <?}?>
    </div>
    <div id="prodData">
        <div class="cart_right">
            <div class="price_right"><?=round($product->product->price,2)?> грн</div>
            <?php

            $form = ActiveForm::begin([
                'id'=>'form-filter',
//                'enableAjaxValidation' => true,
                'enableClientValidation' => true,
                'validateOnSubmit'=>true,
            ]);
            ?>
            <div id="filters">
            <?=include('filterAttr2.php')?>
            </div>
            <?php ActiveForm::end(); ?>
            <script>

            </script>

            <?
            $url=\yii\helpers\Url::toRoute(['catalog/filter','id'=>$product->id]);
            $script = <<< JS
  renderFilters()
                $(document).on('click', ".product-color", function(){
                    $('.select_color ul li a').each(function(){
                        $(this).removeClass('border')
                    })
                    if($('#'+this.id).prop('selected')==true)
                    {
                        $('#'+this.id).prop('selected', false);
                        $(this).removeClass('border')
                    }
                    else
                    {
                        $('#'+this.id).prop('selected', true);
                        $(this).addClass('border')
                    }
                    renderFilters()
                });

                $(document).on('click', ".product-size", function(){
                    $('.select_size ul li a').each(function(){
                        $(this).removeClass('border-size')
                    })

                    if($('#'+this.id).prop('selected')==true)
                    {
                        $('#'+this.id).prop('selected', false);

                        $(this).removeClass('border-size')
                    }
                    else
                    {
                        $('#'+this.id).prop('selected', true);
                        $(this).addClass('border-size')
                    }
                    renderFilters()
                });

                function renderFilters()
                {

                        $.ajax({
                            url: "$url",
                            type: "POST",
                            data: $('#form-filter').serialize(),
                            success: function(data){
//                                alert(data)
                                if(data)
                                {
                                    $('#filters').html(data)
                                }

                            }
                        });

                }
JS;
            $this->registerJs($script, View::POS_END);

            ?>

        </div>
    </div>
</div>
    <div class="clear"></div>
    <div class="description_tab">
        <div class="description_tab">
            <div class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab1" data-toggle="tab">Описание</a></li>
                    <li><a href="#tab2" data-toggle="tab">Оптовикам</a></li>
                    <li><a href="#tab3" data-toggle="tab">Доставка</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab1">
                        <h4><?=$product->name?></h4>
                        <p>
                            <?=$product->description?>
                        </p>
<!--                        <a class="mini_cart_right" href="#">в корзину</a>-->
                        <div class="clear"></div>
                    </div>
                    <div class="tab-pane" id="tab2">
                        <h4>Скидки оптовым покупателям</h4>
                        <p>
                            Действуют оптовые цены.
                            Для получения детальной информации по вопросам оптовых закупок свяжитесь с нашим менеджером по телефону (0482) 31-31-55.
                        </p>
                    </div>
                    <div class="tab-pane" id="tab3">
                        <h4>Стоимость доставки</h4>
                        <img src="/img/dost2.png"/>
                        <p>
                            Доставка заказа осуществляется во все действующие отделения «Новой почты» на территории Украины.<br>
                            Доставка занимает от 1 до 3 дней. После оформления заказа на сайте наши менеджеры перезвонят Вам и согласуют дату доставки заказа перед отправкой.<br><br>
                            Более подробную информацию о графике работы и стоимости доставки Вы можете узнать на сайте «Новой почты» - <a target="_blank" href="http://novaposhta.ua/.">novaposhta.ua</a><br>
                            Оплата заказа производится в отделении или курьеру компании «Нова пошта».<br>
                        </p>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    <div class="similar_products">
<!--        <h4>Похожие товары:</h4>-->
        <div class="similar_products_item">
            <?  if(isset($productPopular) && count($productPopular)>0){ foreach($productPopular as $p)
            {
            ?>
                <div class="similar_products_block"><a href="<?=\yii\helpers\Url::toRoute(['catalog/view','id'=>$p->id])?>">
<?
                        echo  EasyThumbnailImage::thumbnailImg(
                            $p->images[0]->getPath(),
                            500,
                            700,
                            EasyThumbnailImage::THUMBNAIL_INSET,
                            ['alt' => $p->id]
                            );
//                    echo $p->images[0]->getPath();



?>
                </a></div>
            <?}}?>
        </div>
        <div class="clear"></div>


    </div>


</div>
</div>
</div>